services:
  text-replacer:
    build: .
    container_name: text-replacer
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      DICTIONARY_FILE: /app/data/dictionary.json

    volumes:
      - ./data:/app/data
